site_name: SAE Lens 
site_description: Docs for Sparse Autoencoder Training and Analysis Library
site_author: Joseph Bloom
repo_url: http://github.com/jbloomAus/SAELens
repo_name: jbloomAus/SAELens
edit_uri: ""

theme:
  name: material
  font:
    text: Nunito
  palette:
    - scheme: default
      primary: green
      accent: yellow
      background: white
        # Palette toggle for light mode
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: yellow
      background: white
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - navigation.instant

  icon:
    repo: fontawesome/brands/github

    
extra_javascript:
  - assets/saetable.js
  # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  # - javascript/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/saetable.css
nav:
  - Home: index.md
  - Roadmap: roadmap.md
  - Training SAEs: training_saes.md
  - Citation: citation.md
  - Contributing: contributing.md
  - API: api.md
  - Supported SAEs: sae_table.md

plugins:
  - search
  - autorefs
  - section-index
  - mkdocstrings:
      custom_templates: null
      watch:
        - sae_lens/  # Replace with the path to your Python code

hooks:
  - docs/generate_sae_table.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
